server:
  port: 9007
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      server-addr: 192.168.200.128
    gateway:
      discovery:
        locator:
          enabled: false
          filters:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedHeaders: "*"
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      routes:
        #售货机服务
        - id: vmService
          uri: lb://vm-service
          predicates:
            - Path=/vm-service/**
          filters:
            - StripPrefix= 1
        #用户服务
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix= 1
        # 工单服务
        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/task-service/**
          filters:
            - StripPrefix= 1
skipauth: # 指定过滤器放行地址
  urls:
    - /user-service/user/login
    - /vm-service/sku/fileUpload
    - /order-service/wxpay/payNotify
    - /user-service/user/imageCode
    - /user-service/user/code
    - /report/export
    - /vm-service/vm/clientAction